# Generated by Django 3.1.4 on 2020-12-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_auto_20201209_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_main_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
    ]
