# Generated by Django 3.1.3 on 2020-11-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienclouds_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
