# Generated by Django 3.1.3 on 2020-11-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alienclouds_app', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
