# Generated by Django 3.1.3 on 2020-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienclouds_app', '0005_auto_20201125_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_main_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
