# Generated by Django 3.1.4 on 2020-12-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alienclouds_app', '0006_project_project_main_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
