# Generated by Django 3.1.4 on 2020-12-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienclouds_app', '0009_shopitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='images'),
        ),
    ]
